"""
changes the openbox theme for Chameleon theme when our wal script
is called.

Note! openbox config is in .themes! This overrides themes in
/usr/share/themes.

"""

from Color_Grabber import Color_Grabber
from os import environ
from os import system

themerc_path = environ['HOME'] + "/.themes/Chameleon/openbox-3/themerc"
template_path = environ['HOME'] + "/wal-script/default_configs/openbox-3/themerc_template"


def main():

    print("here")
    # extract the colors generated by wal and stored in xresources
    cols = Color_Grabber.grab_colors()

    # dict for formatting the template for themerc
    colors_dict = {
        "col_0": cols[0],
        "col_5": cols[5],
        "col_7": cols[7],
        "col_8": cols[8]
    }

    # grab and format themerc file.
    with open(template_path) as f:
        themerc = f.read().format_map(colors_dict)

    # save the themerc file.
    with open(themerc_path, 'w') as temp:
        temp.write(themerc)

    # refresh openbox
    system("openbox --reconfigure")

    print(":)")

main()
