"""
changes the openbox theme for Chameleon theme when our wal script
is called.

Note! openbox config is in .themes! This overrides themes in
/usr/share/themes.

"""

from Color_Grabber import Color_Grabber
from os import environ
from os import system

themerc_path = environ['HOME'] + "/.themes/Chameleon/openbox-3/themerc"
template_path = environ['HOME'] + "/wal-script/default_configs/openbox-3/themerc_template"


def main():

    # extract the colors generated by wal and stored in xresources
    colors_dict = Color_Grabber.grab_colors_dict()

    # grab and format themerc file.
    with open(template_path, 'r') as f:
        themerc = f.read().format_map(colors_dict)

    # save the themerc file.
    with open(themerc_path, 'w') as temp:
        temp.write(themerc)

    # refresh openbox
    system("openbox --reconfigure")

main()
